/**
 * Convex Auth Configuration
 *
 * This file provides JWT-based authentication helpers for Convex functions.
 * Tokens are generated by the tRPC API and verified using the shared JWT_SECRET.
 *
 * Authentication Flow:
 * 1. User authenticates via tRPC API (phone OTP or password)
 * 2. tRPC API returns JWT access token
 * 3. Client includes token in Convex function calls
 * 4. Convex functions verify token and get userId
 *
 * @see convex/lib/auth.ts for implementation details
 */

// Re-export auth helpers from lib/auth.ts
export {
  requireAuth,
  getOptionalAuth,
  requireAuthUser,
  verifyAccessToken,
} from "./lib/auth";
