#!/usr/bin/env node
/**
 * Version bump script for Togather mobile app.
 *
 * Updates version in all required locations:
 * - app.config.js (version + runtimeVersion + otaVersion)
 * - app.json (version)
 * - ios/Togather/Supporting/Expo.plist (EXUpdatesRuntimeVersion)
 * - .fingerprint (RUNTIME_VERSION)
 *
 * Usage:
 *   node scripts/bump-version.js 1.0.17           # Set specific version
 *   node scripts/bump-version.js patch            # Bump patch: 1.0.16 -> 1.0.17
 *   node scripts/bump-version.js minor            # Bump minor: 1.0.16 -> 1.1.0
 *   node scripts/bump-version.js major            # Bump major: 1.0.16 -> 2.0.0
 *   node scripts/bump-version.js --dry-run 1.0.17 # Preview changes without writing
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const PROJECT_ROOT = path.join(__dirname, "..");

const FILES = {
  appConfig: path.join(PROJECT_ROOT, "app.config.js"),
  appJson: path.join(PROJECT_ROOT, "app.json"),
  expoPlist: path.join(PROJECT_ROOT, "ios", "Togather", "Supporting", "Expo.plist"),
  fingerprint: path.join(PROJECT_ROOT, ".fingerprint"),
};

/**
 * Parse semantic version string into components
 */
function parseVersion(version) {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) {
    return null;
  }
  return {
    major: parseInt(match[1], 10),
    minor: parseInt(match[2], 10),
    patch: parseInt(match[3], 10),
  };
}

/**
 * Compare two versions. Returns:
 *  1 if a > b
 *  0 if a === b
 * -1 if a < b
 */
function compareVersions(a, b) {
  const vA = parseVersion(a);
  const vB = parseVersion(b);

  if (!vA || !vB) return 0;

  if (vA.major !== vB.major) return vA.major > vB.major ? 1 : -1;
  if (vA.minor !== vB.minor) return vA.minor > vB.minor ? 1 : -1;
  if (vA.patch !== vB.patch) return vA.patch > vB.patch ? 1 : -1;
  return 0;
}

/**
 * Get current version from app.config.js
 */
function getCurrentVersion() {
  const content = fs.readFileSync(FILES.appConfig, "utf-8");
  const match = content.match(/version:\s*["']([^"']+)["']/);
  return match ? match[1] : null;
}

/**
 * Calculate new version based on bump type
 */
function calculateNewVersion(current, bumpType) {
  const parsed = parseVersion(current);
  if (!parsed) {
    console.error(`Invalid current version: ${current}`);
    process.exit(1);
  }

  switch (bumpType) {
    case "major":
      return `${parsed.major + 1}.0.0`;
    case "minor":
      return `${parsed.major}.${parsed.minor + 1}.0`;
    case "patch":
      return `${parsed.major}.${parsed.minor}.${parsed.patch + 1}`;
    default:
      // Assume it's a specific version
      if (parseVersion(bumpType)) {
        return bumpType;
      }
      console.error(`Invalid version or bump type: ${bumpType}`);
      console.error("Use: major, minor, patch, or a specific version (e.g., 1.0.17)");
      process.exit(1);
  }
}

/**
 * Update app.config.js with new version
 */
function updateAppConfig(newVersion, dryRun) {
  let content = fs.readFileSync(FILES.appConfig, "utf-8");

  // Update version
  content = content.replace(
    /version:\s*["'][^"']+["']/,
    `version: "${newVersion}"`
  );

  // Update runtimeVersion
  content = content.replace(
    /runtimeVersion:\s*["'][^"']+["']/,
    `runtimeVersion: "${newVersion}"`
  );

  // Update otaVersion default (the fallback value)
  content = content.replace(
    /otaVersion:\s*process\.env\.OTA_VERSION\s*\|\|\s*["'][^"']+["']/,
    `otaVersion: process.env.OTA_VERSION || "${newVersion}"`
  );

  if (!dryRun) {
    fs.writeFileSync(FILES.appConfig, content);
  }

  return true;
}

/**
 * Update app.json with new version
 */
function updateAppJson(newVersion, dryRun) {
  const content = JSON.parse(fs.readFileSync(FILES.appJson, "utf-8"));
  content.expo.version = newVersion;

  if (!dryRun) {
    fs.writeFileSync(FILES.appJson, JSON.stringify(content, null, 2) + "\n");
  }

  return true;
}

/**
 * Update Expo.plist with new runtime version
 */
function updateExpoPlist(newVersion, dryRun) {
  if (!fs.existsSync(FILES.expoPlist)) {
    console.log(`  - ios/Togather/Supporting/Expo.plist (skipped - generated by prebuild)`);
    return false;
  }

  let content = fs.readFileSync(FILES.expoPlist, "utf-8");

  // Update EXUpdatesRuntimeVersion
  content = content.replace(
    /(<key>EXUpdatesRuntimeVersion<\/key>\s*<string>)[^<]+(<\/string>)/,
    `$1${newVersion}$2`
  );

  if (!dryRun) {
    fs.writeFileSync(FILES.expoPlist, content);
  }

  return true;
}

/**
 * Update .fingerprint with new runtime version and regenerate hash
 */
function updateFingerprint(newVersion, dryRun) {
  if (!dryRun) {
    // Run the fingerprint script to regenerate with new version
    try {
      execSync("node scripts/check-fingerprint.js --update", {
        cwd: PROJECT_ROOT,
        stdio: "inherit",
      });
    } catch (error) {
      console.error("Failed to update fingerprint");
      return false;
    }
  }

  return true;
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const versionArg = args.find((arg) => !arg.startsWith("--"));

  if (!versionArg) {
    console.log("Usage: node scripts/bump-version.js [--dry-run] <version|major|minor|patch>");
    console.log("");
    console.log("Examples:");
    console.log("  node scripts/bump-version.js 1.0.17    # Set specific version");
    console.log("  node scripts/bump-version.js patch     # 1.0.16 -> 1.0.17");
    console.log("  node scripts/bump-version.js minor     # 1.0.16 -> 1.1.0");
    console.log("  node scripts/bump-version.js major     # 1.0.16 -> 2.0.0");
    process.exit(1);
  }

  const currentVersion = getCurrentVersion();
  if (!currentVersion) {
    console.error("Could not read current version from app.config.js");
    process.exit(1);
  }

  const newVersion = calculateNewVersion(currentVersion, versionArg);

  console.log(`Current version: ${currentVersion}`);
  console.log(`New version:     ${newVersion}`);

  // Validate version is increasing
  if (compareVersions(newVersion, currentVersion) <= 0) {
    console.error("");
    console.error(`Error: New version (${newVersion}) must be greater than current (${currentVersion})`);
    process.exit(1);
  }

  if (dryRun) {
    console.log("");
    console.log("Dry run - no files will be modified");
    console.log("");
  }

  console.log("");
  console.log("Updating files:");

  // Update all files
  console.log(`  - app.config.js`);
  updateAppConfig(newVersion, dryRun);

  console.log(`  - app.json`);
  updateAppJson(newVersion, dryRun);

  // Only update Expo.plist if ios folder exists (it's gitignored, generated by prebuild)
  if (fs.existsSync(FILES.expoPlist)) {
    console.log(`  - ios/Togather/Supporting/Expo.plist`);
    updateExpoPlist(newVersion, dryRun);
  } else {
    console.log(`  - ios/Togather/Supporting/Expo.plist (skipped - will be set by prebuild)`);
  }

  if (!dryRun) {
    console.log(`  - .fingerprint (regenerating hash)`);
    updateFingerprint(newVersion, dryRun);
  }

  console.log("");
  if (dryRun) {
    console.log("Dry run complete. Run without --dry-run to apply changes.");
  } else {
    console.log(`Done! Version bumped to ${newVersion}`);
    console.log("");
    console.log("Next steps:");
    console.log("  1. Review changes: git diff");
    console.log("  2. Commit: git add -A && git commit -m 'chore: bump version to " + newVersion + "'");
    console.log("  3. Push to trigger builds");
  }
}

main().catch((error) => {
  console.error("Error:", error);
  process.exit(1);
});
