/**
 * ChatWallpaper — the patterned backdrop behind a WhatsApp-shell chat room.
 *
 * WA-VISUAL-DELTAS.md §S4.1: "cream with the line-art doodle pattern at low
 * opacity — bundle a static wallpaper asset (PNG, `require()`, plus dark
 * variant), NOT a flat tint. Applied to the whole thread area and under the
 * translucent nav/composer."
 *
 * Renders as an absolutely-positioned, non-interactive layer so the chat
 * room can drop it once behind *everything* (header, tab strip, message list,
 * composer) rather than per-section. The base fill comes from the theme's
 * `chatWallpaper` token; the tile is transparent ink that repeats over it, so
 * a future per-community wallpaper only needs the token to change.
 *
 * The tiles are original artwork generated by
 * `scripts/generate-chat-wallpaper.mjs` — WhatsApp's own doodle wallpaper is
 * copyrighted and is deliberately NOT used.
 *
 * Flag-on only: nothing renders this unless `useWhatsappShell()` is true.
 */
import React from 'react';
import { Image, StyleSheet, View } from 'react-native';
import { useTheme } from '@hooks/useTheme';

const WALLPAPER_TILE_LIGHT = require('@/assets/images/chat-wallpaper-light.png');
const WALLPAPER_TILE_DARK = require('@/assets/images/chat-wallpaper-dark.png');

export function ChatWallpaper() {
  const { colors, isDark } = useTheme();
  return (
    <View
      testID="chat-wallpaper"
      pointerEvents="none"
      style={[StyleSheet.absoluteFill, { backgroundColor: colors.chatWallpaper }]}
    >
      <Image
        testID="chat-wallpaper-tile"
        source={isDark ? WALLPAPER_TILE_DARK : WALLPAPER_TILE_LIGHT}
        style={StyleSheet.absoluteFill}
        // `repeat` tiles the 512px doodle sheet across the whole surface
        // (supported on iOS, Android and react-native-web, which maps it to
        // `background-repeat: repeat`).
        resizeMode="repeat"
      />
    </View>
  );
}
