/**
 * ChatWallpaper — the patterned backdrop behind a WhatsApp-shell chat room.
 *
 * WA-VISUAL-DELTAS.md §S4.1: "cream with the line-art doodle pattern at low
 * opacity — bundle a static wallpaper asset (PNG, `require()`, plus dark
 * variant), NOT a flat tint. Applied to the whole thread area and under the
 * translucent nav/composer."
 *
 * Renders as an absolutely-positioned, non-interactive layer so the chat
 * room can drop it once behind *everything* (header, tab strip, message list,
 * composer) rather than per-section. The base fill comes from the theme's
 * `chatWallpaper` token; the tile is transparent ink that repeats over it, so
 * a future per-community wallpaper only needs the token to change.
 *
 * ## Why the tiling is hand-rolled
 *
 * The first cut used a single absolute-fill `<Image resizeMode="repeat">`.
 * That reads correctly on web (RN-Web maps it to `background-repeat: repeat`)
 * but on a real device UIKit does NOT tile it — it stretched the sheet across
 * the whole screen, so the 6%-alpha doodles smeared into what looked like a
 * flat cream tint (owner's device recording, 2026-07-29). So we lay out an
 * explicit grid of `TILE`-sized images instead: plain layout, no resize mode,
 * identical on iOS / Android / web. The tile PNG is authored at exactly `TILE`
 * px by `scripts/generate-chat-wallpaper.mjs`, so each image draws 1:1 with no
 * scaling.
 *
 * The tiles are original artwork generated by that script — WhatsApp's own
 * doodle wallpaper is copyrighted and is deliberately NOT used.
 *
 * Flag-on only: nothing renders this unless `useWhatsappShell()` is true.
 */
import React from 'react';
import { Image, StyleSheet, useWindowDimensions, View } from 'react-native';
import { useTheme } from '@hooks/useTheme';

const WALLPAPER_TILE_LIGHT = require('@/assets/images/chat-wallpaper-light.png');
const WALLPAPER_TILE_DARK = require('@/assets/images/chat-wallpaper-dark.png');

/**
 * Edge length of one doodle tile, in points — must stay in sync with `TILE` in
 * `scripts/generate-chat-wallpaper.mjs` (the PNGs are authored at this size).
 */
export const WALLPAPER_TILE_SIZE = 256;

export function ChatWallpaper() {
  const { colors, isDark } = useTheme();
  const { width, height } = useWindowDimensions();

  // Cover the window exactly — the layer is absolutely positioned inside a
  // full-screen host, so anything past the window edge is wasted work.
  const columns = Math.max(1, Math.ceil(width / WALLPAPER_TILE_SIZE));
  const rows = Math.max(1, Math.ceil(height / WALLPAPER_TILE_SIZE));
  const source = isDark ? WALLPAPER_TILE_DARK : WALLPAPER_TILE_LIGHT;

  return (
    <View
      testID="chat-wallpaper"
      pointerEvents="none"
      style={[StyleSheet.absoluteFill, { backgroundColor: colors.chatWallpaper }]}
    >
      <View style={styles.grid} pointerEvents="none">
        {Array.from({ length: columns * rows }, (_, i) => (
          <Image
            key={i}
            testID="chat-wallpaper-tile"
            source={source}
            style={styles.tile}
          />
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  // `flexWrap` + fixed-size children is what does the tiling: the row fills
  // left-to-right and wraps every `columns` tiles. `overflow: hidden` keeps
  // the final partial row/column from painting outside the layer.
  grid: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    flexWrap: 'wrap',
    overflow: 'hidden',
  },
  tile: {
    width: WALLPAPER_TILE_SIZE,
    height: WALLPAPER_TILE_SIZE,
  },
});
