/**
 * ChatWallpaper — the patterned backdrop behind a WhatsApp-shell chat room.
 *
 * WA-VISUAL-DELTAS.md §S4.1: "cream with the line-art doodle pattern at low
 * opacity — bundle a static wallpaper asset, plus dark variant, NOT a flat
 * tint. Applied to the whole thread area and under the translucent
 * nav/composer."
 *
 * Renders as an absolutely-positioned, non-interactive layer so the chat
 * room can drop it once behind *everything* (header, tab strip, message list,
 * composer) rather than per-section. The base fill comes from the theme's
 * `chatWallpaper` token; the tile is transparent ink that repeats over it, so
 * a future per-community wallpaper only needs the token to change.
 *
 * ## Why the tiling is hand-rolled
 *
 * The first cut used a single absolute-fill `<Image resizeMode="repeat">`.
 * That reads correctly on web (RN-Web maps it to `background-repeat: repeat`)
 * but on a real device UIKit does NOT tile it — it stretched the sheet across
 * the whole screen, so the 6%-alpha doodles smeared into what looked like a
 * flat cream tint (owner's device recording, 2026-07-29). So we lay out an
 * explicit grid of `TILE`-sized images instead: plain layout, no resize mode,
 * identical on iOS / Android / web. The tile PNG is authored at exactly `TILE`
 * px by `scripts/generate-chat-wallpaper.mjs`, so each image draws 1:1 with no
 * scaling.
 *
 * The tiles are original artwork generated by that script — WhatsApp's own
 * doodle wallpaper is copyrighted and is deliberately NOT used.
 *
 * ## Why the tiles are data URIs, not `require()`d PNGs
 *
 * They used to be `assets/images/chat-wallpaper-*.png`. That works in the
 * simulator, where Metro serves assets off the dev server — but NOT on a device
 * running an OTA update: the PNGs were newer than the installed binary, so
 * expo-updates had to ship them as downloaded *assets*, and on device they
 * never resolved. The wallpaper rendered as flat cream while the rest of the
 * same bundle was fine (owner report, 2026-07-30). Inlining them as base64
 * removes the whole failure class — a string in the JS bundle cannot go
 * missing. `source={{ uri }}` carries no intrinsic size, which is why the
 * explicit `width`/`height` on `styles.tile` below are load-bearing.
 *
 * Flag-on only: nothing renders this unless `useWhatsappShell()` is true.
 */
import React from 'react';
import { Image, StyleSheet, useWindowDimensions, View } from 'react-native';
import { useTheme } from '@hooks/useTheme';
import {
  WALLPAPER_TILE_DARK_URI,
  WALLPAPER_TILE_LIGHT_URI,
} from '../chatWallpaperTiles';

/**
 * Edge length of one doodle tile, in points — must stay in sync with `TILE` in
 * `scripts/generate-chat-wallpaper.mjs` (the tiles are authored at this size).
 */
export const WALLPAPER_TILE_SIZE = 256;

// Module-level so every tile shares one source object and it never changes
// identity across renders.
const LIGHT_TILE_SOURCE = { uri: WALLPAPER_TILE_LIGHT_URI } as const;
const DARK_TILE_SOURCE = { uri: WALLPAPER_TILE_DARK_URI } as const;

export function ChatWallpaper() {
  const { colors, isDark } = useTheme();
  const { width, height } = useWindowDimensions();

  // Cover the window exactly — the layer is absolutely positioned inside a
  // full-screen host, so anything past the window edge is wasted work.
  const columns = Math.max(1, Math.ceil(width / WALLPAPER_TILE_SIZE));
  const rows = Math.max(1, Math.ceil(height / WALLPAPER_TILE_SIZE));
  const source = isDark ? DARK_TILE_SOURCE : LIGHT_TILE_SOURCE;

  return (
    <View
      testID="chat-wallpaper"
      pointerEvents="none"
      style={[StyleSheet.absoluteFill, { backgroundColor: colors.chatWallpaper }]}
    >
      <View style={styles.grid} pointerEvents="none">
        {/* Absolutely place each tile: flexWrap can only fit whole tiles per
            row (one 256pt tile on a 390pt phone), leaving the remainder
            untextured — explicit coordinates let edge tiles overflow and
            clip instead. */}
        {Array.from({ length: columns * rows }, (_, i) => (
          <Image
            key={i}
            testID="chat-wallpaper-tile"
            source={source}
            style={[
              styles.tile,
              {
                left: (i % columns) * WALLPAPER_TILE_SIZE,
                top: Math.floor(i / columns) * WALLPAPER_TILE_SIZE,
              },
            ]}
          />
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  // Tiles are absolutely positioned at explicit (col, row) coordinates;
  // `overflow: hidden` clips the partial tiles at the right/bottom edges.
  grid: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  tile: {
    position: 'absolute',
    width: WALLPAPER_TILE_SIZE,
    height: WALLPAPER_TILE_SIZE,
  },
});
