import { Link } from "react-router-dom";
import type { ReactNode } from "react";

/**
 * Developer documentation for the public Attendance API.
 *
 * This is a browser-only page. It is intentionally excluded from the mobile
 * app's universal/app links so it never opens inside the native app:
 * - iOS: listed in `excludedPaths` of the AASA file generated by
 *   apps/link-preview/cloudflare-worker.js.
 * - Routing: "/developers" is in that worker's LANDING_PAGE_PATHS, so it is
 *   served by this Vite site (not treated as a community slug or app route).
 * - Android: only /e/, /g/, /nearme, /c/, /a/ are registered app-link
 *   prefixes (apps/mobile/app.config.js), so /developers stays in the browser.
 * Keep those in sync if this path ever changes.
 */
export function Developers() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-neutral-600 hover:text-neutral-900 mb-8"
        >
          <svg
            className="w-5 h-5"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>

        <p className="text-sm font-semibold uppercase tracking-wide text-neutral-400 mb-2">
          Developer API
        </p>
        <h1 className="text-4xl font-bold text-neutral-900 mb-3">
          Attendance API
        </h1>
        <p className="text-lg text-neutral-600 leading-relaxed mb-10">
          A read-only HTTP API for pulling a community&rsquo;s group attendance
          data out of Togather &mdash; for dashboards, reporting, or syncing into
          another system. Togather is the source of truth for which events exist
          and who attended; integrate against this API rather than duplicating
          that data elsewhere.
        </p>

        <Section title="At a glance">
          <ul className="list-disc pl-6 text-neutral-600 space-y-1">
            <li>
              <Strong>Read-only.</Strong> The API returns data; it never creates
              or modifies anything in Togather.
            </li>
            <li>
              <Strong>Aggregate counts only.</Strong> You get tallies per event
              (attended, guests, RSVP counts) &mdash; never names or any other
              personal information.
            </li>
            <li>
              <Strong>Community-scoped.</Strong> An API key only sees data for
              the community that issued it.
            </li>
            <li>
              <Strong>All groups.</Strong> Every group type in the community is
              covered, with an optional filter to narrow to one type.
            </li>
          </ul>
        </Section>

        <Section title="1. Get an API key">
          <P>
            API keys are created and revoked by a community admin in the mobile
            app:
          </P>
          <p className="text-neutral-800 font-medium bg-neutral-100 rounded-lg px-4 py-3 my-4">
            Admin &rarr; Settings &rarr; Developer &rarr; API Keys
          </p>
          <ul className="list-disc pl-6 text-neutral-600 space-y-1">
            <li>
              The raw key is shown <Strong>exactly once</Strong>, right after you
              create it. Copy it then &mdash; it can&rsquo;t be retrieved later.
            </li>
            <li>
              Only a hash of the key is stored. If a key is lost or leaked,
              revoke it and create a new one.
            </li>
            <li>
              Revoking a key takes effect immediately; requests using it start
              returning <Code>401</Code>.
            </li>
            <li>
              The exact base URL for your community is shown on that same screen.
            </li>
          </ul>
        </Section>

        <Section title="2. Authentication">
          <P>Send the key as a bearer token on every request:</P>
          <CodeBlock>{`Authorization: Bearer tgk_xxxxxxxxxxxxxxxxxxxxxxxx`}</CodeBlock>
          <P>
            A <Code>x-api-key: tgk_…</Code> header is also accepted. Requests with
            a missing, invalid, or revoked key return <Code>401</Code>.
          </P>
        </Section>

        <Section title="3. Endpoint">
          <CodeBlock>{`GET https://<your-deployment>.convex.site/api/v1/attendance`}</CodeBlock>
          <P>
            <Code>{"<your-deployment>"}</Code> is specific to your community and
            is shown on the API Keys screen. All parameters are optional.
          </P>

          <h4 className="font-semibold text-neutral-800 mt-6 mb-3">
            Query parameters
          </h4>
          <Table
            headers={["Parameter", "Type", "Description"]}
            rows={[
              ["since", "Unix ms or ISO date", "Only events scheduled at or after this time."],
              ["until", "Unix ms or ISO date", "Only events scheduled at or before this time."],
              ["groupType", "string (slug)", "Limit to one group type, e.g. dinner-parties."],
              ["status", "string", "scheduled, completed, or cancelled."],
              ["limit", "integer", "Max events to return. Default 200, max 1000."],
            ]}
          />
          <Callout>
            Events come back newest-first. <Code>since</Code> and{" "}
            <Code>until</Code> filter on each event&rsquo;s scheduled date &mdash;
            not on when attendance was recorded &mdash; so they are a date
            window, not a change cursor. To keep a dashboard current (including
            attendance edited <em>after</em> an event happened), re-pull a
            trailing window each poll (e.g. the last 90 days) rather than
            advancing a cursor to &ldquo;now.&rdquo; When <Code>hasMore</Code> is{" "}
            <Code>true</Code>, more matching events exist than were returned
            &mdash; narrow the window to page through them.
          </Callout>
        </Section>

        <Section title="4. Response">
          <P>
            <Code>200 OK</Code> with a JSON body. One object per event (meeting);
            a recurring dinner party appears as several events across dates.
          </P>
          <CodeBlock>{`{
  "community": { "id": "...", "name": "Fount", "subdomain": "fount" },
  "generatedAt": "2026-06-16T14:22:13.000Z",
  "limit": 200,
  "hasMore": false,
  "events": [
    {
      "id": "...",
      "title": "Tuesday Dinner Party",
      "scheduledAt": "2026-06-10T23:00:00.000Z",
      "status": "completed",
      "group": {
        "id": "...",
        "name": "Tuesday Dinner",
        "groupType": "Dinner Parties",
        "groupTypeSlug": "dinner-parties"
      },
      "attendance": {
        "attended": 12,
        "guests": 3,
        "rsvps": { "going": 14, "notGoing": 1, "maybe": 2, "guestsExpected": 5 }
      }
    }
  ]
}`}</CodeBlock>

          <h4 className="font-semibold text-neutral-800 mt-6 mb-3">Fields</h4>
          <Table
            headers={["Field", "Meaning"]}
            rows={[
              ["events[].id", "Stable identifier for the event."],
              ["events[].title", "Event title. May be null (events don't require one)."],
              ["events[].scheduledAt", "Event date/time, ISO 8601 (UTC)."],
              ["events[].status", "scheduled | completed | cancelled."],
              ["group.name / groupType", "Group label and its type. groupTypeSlug is the value to pass to ?groupType."],
              ["attendance.attended", "Number of members marked present."],
              ["attendance.guests", "Number of guest (non-member) records logged for the event."],
              ["attendance.rsvps.going / notGoing / maybe", "RSVP tallies."],
              ["attendance.rsvps.guestsExpected", "Sum of plus-ones declared by 'going' RSVPs."],
              ["hasMore", "true if more matching events exist beyond the returned limit."],
            ]}
          />
        </Section>

        <Section title="5. What's possible">
          <ul className="list-disc pl-6 text-neutral-600 space-y-1">
            <li>Pull attendance, guest, and RSVP counts for every event in the community.</li>
            <li>Filter by date range, group type, and event status.</li>
            <li>Build dashboards and charts of attendance over time (e.g. dinner-party turnout per week).</li>
            <li>Keep a dashboard current by re-pulling a trailing date window on your own schedule &mdash; counts update as attendance is recorded.</li>
            <li>Compare turnout across groups of the same type using the per-event group labels.</li>
          </ul>
        </Section>

        <Section title="6. What's not possible">
          <ul className="list-disc pl-6 text-neutral-600 space-y-1">
            <li>
              <Strong>No personal data.</Strong> You cannot retrieve who attended
              &mdash; no names, phone numbers, emails, or user IDs. Only counts.
            </li>
            <li>
              <Strong>Read-only.</Strong> You cannot create, edit, or delete
              events, attendance, RSVPs, groups, or members.
            </li>
            <li>
              <Strong>No push / webhooks.</Strong> Updates aren&rsquo;t pushed to
              you; poll the endpoint on an interval that suits your needs.
            </li>
            <li>
              <Strong>Single community per key.</Strong> A key cannot read across
              communities; issue one key per community you integrate.
            </li>
            <li>
              <Strong>Counts, not rosters.</Strong> There is no per-attendee
              breakdown and no message, chat, or financial data.
            </li>
            <li>
              <Strong>Bounded responses.</Strong> A single call returns at most
              1000 events; use date filters to cover larger histories.
            </li>
          </ul>
        </Section>

        <Section title="7. Errors">
          <Table
            headers={["Status", "Meaning"]}
            rows={[
              ["401", "Missing, invalid, or revoked API key."],
              ["400", "Invalid since, until, status, or limit parameter."],
              ["500", "Unexpected server error."],
            ]}
          />
          <P>All errors return a JSON body of the form <Code>{`{ "error": "..." }`}</Code>.</P>
        </Section>

        <Section title="8. Example integration">
          <P>Fetch completed dinner-party events since the start of the year:</P>
          <CodeBlock>{`curl -H "Authorization: Bearer $TOGATHER_API_KEY" \\
  "https://<deployment>.convex.site/api/v1/attendance?groupType=dinner-parties&status=completed&since=2026-01-01"`}</CodeBlock>

          <P>
            Refreshing a trailing window on each poll (re-upsert so attendance
            recorded after an event is picked up):
          </P>
          <CodeBlock>{`const BASE = "https://<deployment>.convex.site/api/v1/attendance";

// 'since'/'until' filter on the EVENT date, not on when attendance changed.
// There is no "updated since" cursor, so re-pull a trailing window each run
// and upsert — that way late attendance edits to recently-scheduled events
// are always reflected.
async function refreshWindow(daysBack = 90) {
  const since = new Date(Date.now() - daysBack * 864e5).toISOString();
  const url = new URL(BASE);
  url.searchParams.set("since", since);
  url.searchParams.set("limit", "1000");

  const res = await fetch(url, {
    headers: { Authorization: \`Bearer \${process.env.TOGATHER_API_KEY}\` },
  });
  if (!res.ok) throw new Error(\`Attendance API \${res.status}\`);

  const data = await res.json();
  for (const event of data.events) {
    // event.attendance.attended, event.attendance.rsvps.going, ...
    upsertIntoDashboard(event); // keyed by event.id
  }
  // If data.hasMore is true, widen the window or page with an older 'until'.
  return data.hasMore;
}`}</CodeBlock>
        </Section>

        <Section title="Notes for automated/LLM consumers">
          <ul className="list-disc pl-6 text-neutral-600 space-y-1">
            <li>Base path is versioned: <Code>/api/v1/attendance</Code>.</li>
            <li>Authentication is a bearer token only; there is no OAuth flow and no cookie/session.</li>
            <li>
              <Code>groupType</Code> expects the <Code>groupTypeSlug</Code> value
              from a prior response; slugs are defined per community and are not
              global constants.
            </li>
            <li>Timestamps in responses are ISO 8601 UTC strings; request filters accept ISO strings or Unix milliseconds.</li>
            <li><Code>since</Code>/<Code>until</Code> filter on each event&rsquo;s scheduled date, not on when attendance was recorded. There is no &ldquo;updated since&rdquo; change cursor &mdash; to capture late attendance edits, re-pull a trailing date window rather than advancing a cursor.</li>
            <li>Treat the response as additive &mdash; new fields may appear over time; do not assume a fixed key set.</li>
            <li>There is exactly one resource; pagination is by date range, not cursors or offsets.</li>
          </ul>
        </Section>

        <p className="text-sm text-neutral-400 mt-12 border-t border-neutral-100 pt-6">
          Questions or need a key for your community? Contact your Togather admin
          or reach out at togather@supa.media.
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-2xl font-bold text-neutral-900 mb-4">{title}</h2>
      {children}
    </section>
  );
}

function P({ children }: { children: ReactNode }) {
  return <p className="text-neutral-600 leading-relaxed mb-3">{children}</p>;
}

function Strong({ children }: { children: ReactNode }) {
  return <span className="font-semibold text-neutral-800">{children}</span>;
}

function Code({ children }: { children: ReactNode }) {
  return (
    <code className="font-mono text-[0.85em] bg-neutral-100 text-neutral-800 rounded px-1.5 py-0.5">
      {children}
    </code>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="bg-neutral-900 text-neutral-100 rounded-lg p-4 my-4 overflow-x-auto text-sm leading-relaxed">
      <code className="font-mono whitespace-pre">{children}</code>
    </pre>
  );
}

function Callout({ children }: { children: ReactNode }) {
  return (
    <div className="border-l-4 border-neutral-300 bg-neutral-50 rounded-r-lg px-4 py-3 my-4 text-neutral-600 text-sm leading-relaxed">
      {children}
    </div>
  );
}

function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  return (
    <div className="overflow-x-auto my-4">
      <table className="w-full text-left text-sm border-collapse">
        <thead>
          <tr className="border-b border-neutral-200">
            {headers.map((h) => (
              <th key={h} className="py-2 pr-4 font-semibold text-neutral-800 align-top">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-b border-neutral-100 align-top">
              {row.map((cell, j) => (
                <td
                  key={j}
                  className={
                    j === 0
                      ? "py-2 pr-4 font-mono text-[0.85em] text-neutral-800 whitespace-nowrap"
                      : "py-2 pr-4 text-neutral-600"
                  }
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
